import Footer from '@/app/components/footer/Footer'
import Navbar from '@/app/components/navbar/Navebar'
import './globals.css'

import { UseThemeProvider } from '@/context/ThemContext'
import ThemeProvider from '@/providers/ThemeProvider'
import { crimson_Text, josefin_Sans, montserrat } from '@/styles/fonts'
import AuthProvider from '@/providers/AuthProvider'


export const metadata = {
  title: 'Vision Blog ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${montserrat.variable} ${crimson_Text.variable} ${josefin_Sans.variable}`}>
        <AuthProvider>
        <UseThemeProvider>
          <ThemeProvider>

            <div className='container'>
              <div className='wrapper'>
                <Navbar />
                {children}
                <Footer />
              </div>

            </div>
          </ThemeProvider>
        </UseThemeProvider>
        </AuthProvider>
       

      </body>
    </html>
  )
}
